// Generated by Wrangler by running `wrangler types --env-interface Env`

interface Env {
	ALLOWED_DOMAINS: "company.com";
	DEFAULT_DESTINATION: "https://company.com";
	ANALYTICS: AnalyticsEngineDataset;
}
